name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-c:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    
    - name: make
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-executable
        path: |
          main_cpp
          main_cpp.exe
  
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts from previous build
      uses: actions/download-artifact@v2
      with:
        name: build-executable

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }} 
        automatic_release_tag: 'latest'
        prerelease: true
        title: 'Development Build'
        files: |
          build-executable.zip
      if: ${{ github.event_name == 'push' }}
