name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-c:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-data
        path: build/
